# Generated by Django 4.2.4 on 2024-05-17 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Akun',
            fields=[
                ('email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('nama', models.CharField(max_length=100)),
                ('gender', models.IntegerField()),
                ('tempat_lahir', models.CharField(max_length=50)),
                ('tanggal_lahir', models.DateField()),
                ('is_verified', models.BooleanField()),
                ('kota_asal', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'akun',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('judul', models.CharField(max_length=100)),
                ('jumlah_lagu', models.IntegerField()),
                ('id_label', models.UUIDField(blank=True, null=True)),
                ('total_durasi', models.IntegerField()),
            ],
            options={
                'db_table': 'album',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'artist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('tipe', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'chart',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id_episode', models.UUIDField(primary_key=True, serialize=False)),
                ('judul', models.CharField(max_length=100)),
                ('deskripsi', models.CharField(max_length=500)),
                ('durasi', models.IntegerField()),
                ('tanggal_rilis', models.DateField()),
            ],
            options={
                'db_table': 'episode',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Konten',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('judul', models.CharField(max_length=100)),
                ('tanggal_rilis', models.DateField()),
                ('tahun', models.IntegerField()),
                ('durasi', models.IntegerField()),
            ],
            options={
                'db_table': 'konten',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('kontak', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'label',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Paket',
            fields=[
                ('jenis', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('harga', models.IntegerField()),
            ],
            options={
                'db_table': 'paket',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PemilikHakCipta',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('rate_royalti', models.IntegerField()),
            ],
            options={
                'db_table': 'pemilik_hak_cipta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'playlist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Songwriter',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'songwriter',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('timestamp_dimulai', models.DateTimeField()),
                ('timestamp_berakhir', models.DateTimeField()),
                ('metode_bayar', models.CharField(max_length=50)),
                ('nominal', models.IntegerField()),
            ],
            options={
                'db_table': 'transaction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AkunPlaySong',
            fields=[
                ('email_pemain', models.OneToOneField(db_column='email_pemain', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='main.akun')),
                ('waktu', models.DateTimeField()),
            ],
            options={
                'db_table': 'akun_play_song',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AkunPlayUserPlaylist',
            fields=[
                ('email_pemain', models.OneToOneField(db_column='email_pemain', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='main.akun')),
                ('email_pembuat', models.CharField(max_length=50)),
                ('waktu', models.DateTimeField()),
            ],
            options={
                'db_table': 'akun_play_user_playlist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id_konten', models.OneToOneField(db_column='id_konten', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='main.konten')),
                ('genre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'genre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nonpremium',
            fields=[
                ('email', models.OneToOneField(db_column='email', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='main.akun')),
            ],
            options={
                'db_table': 'nonpremium',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlaylistSong',
            fields=[
                ('id_playlist', models.OneToOneField(db_column='id_playlist', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='main.playlist')),
            ],
            options={
                'db_table': 'playlist_song',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id_konten', models.OneToOneField(db_column='id_konten', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='main.konten')),
            ],
            options={
                'db_table': 'podcast',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Podcaster',
            fields=[
                ('email', models.OneToOneField(db_column='email', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='main.akun')),
            ],
            options={
                'db_table': 'podcaster',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Premium',
            fields=[
                ('email', models.OneToOneField(db_column='email', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='main.akun')),
            ],
            options={
                'db_table': 'premium',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Royalti',
            fields=[
                ('id_pemilik_hak_cipta', models.OneToOneField(db_column='id_pemilik_hak_cipta', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='main.pemilikhakcipta')),
                ('jumlah', models.IntegerField()),
            ],
            options={
                'db_table': 'royalti',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id_konten', models.OneToOneField(db_column='id_konten', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='main.konten')),
                ('id_album', models.UUIDField(blank=True, null=True)),
                ('total_play', models.IntegerField()),
                ('total_download', models.IntegerField()),
            ],
            options={
                'db_table': 'song',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SongwriterWriteSong',
            fields=[
                ('id_songwriter', models.OneToOneField(db_column='id_songwriter', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='main.songwriter')),
            ],
            options={
                'db_table': 'songwriter_write_song',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserPlaylist',
            fields=[
                ('email_pembuat', models.OneToOneField(db_column='email_pembuat', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='main.akun')),
                ('id_user_playlist', models.UUIDField(unique=True)),
                ('judul', models.CharField(max_length=100)),
                ('deskripsi', models.CharField(max_length=500)),
                ('jumlah_lagu', models.IntegerField()),
                ('tanggal_dibuat', models.DateField()),
                ('total_durasi', models.IntegerField()),
            ],
            options={
                'db_table': 'user_playlist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='session',
            fields=[
                ('email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('nama', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DownloadedSong',
            fields=[
                ('id_song', models.OneToOneField(db_column='id_song', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='main.song')),
            ],
            options={
                'db_table': 'downloaded_song',
                'managed': False,
            },
        ),
    ]
